### ISSUE TITLE
Hellen81 test case

### ISSUE THREAD

**Issue by rusefillc** [frank-f/gerbmerge#3]
TL, DR: can we have https://github.com/rusefi/gerbmerge/tree/rusefi-tests/examples/hellen81-a work on this fork? in that folder there is full input and expected output.

Longer story: https://github.com/rusefi/rusefi is an open source project for internal combustion engine control unit. In order to facilitate plug-in boards for different vehicles/different connectors with reusable functional blocks @andreika-git has created https://github.com/andreika-git/hellen-one/ with is GerbMerge+PdfMerge+SomethingElseMerge+actual reusable modules to use

https://github.com/andreika-git/hellen81 would be a specific ECU which was developed using that framework

I believe that hellen81 specifically has only Altium Designer gerber files as opposed to other rusEFI boards which often use KiCAD 6.

**Comment by rusefillc** [comment]
PS: and even wider context is our desire to migrate that framework to Python 3 https://github.com/andreika-git/hellen-one/issues/130

**Comment by rusefillc** [comment]
Status update: I've created https://github.com/rusefi/gerbmerge/tree/rusefi-tests-based-on-frank-f branch which is https://github.com/frank-f/gerbmerge master with our test file commits on top

At the moment hellen81 test case fail with the following error message:
![image](https://user-images.githubusercontent.com/48498823/150704088-3f38e5e4-cbf1-4f17-83f0-97e0d439132f.png)

hellen121 test case fails with the same
![image](https://user-images.githubusercontent.com/48498823/150704107-855a6e94-6754-45eb-a99e-d99faa8d96ea.png)


@andreika-git any idea what is this about?

**Comment by frank-f** [comment]
Without looking at your project, I suspect you didn't change the name of the drills layer in your configuration file, right?

Since I needed gerbmerge to work with two drill files (PTH and NPTH) in one of my last projects, the layers are now called drillspth and drillsnpth. If you have just one drills file, [use drillspth](https://github.com/frank-f/gerbmerge/blob/d46e529f0beaaa8bff93f2f1e0bc89d36ac1e73e/gerbmerge/config.py#L308).

**Comment by rusefillc** [comment]
Great! With option rename https://github.com/rusefi/gerbmerge/commit/3eb61dececbffc046205882daeaca5e7851b40db I got the script to work! But our drill files contain both PLATED and NON_PLATED so this does not look right. (open question 1) Does your fork still support combined drill files or does your fork require separate files?

(open question 2) Another concern with format/precision, even if we disregard plated/non plated issue for now:


We have
``T8F00S00C0.0984`` 
which in our fork becomes ``T07C0.098400`` but in your fork it becomes ``T07C0.098`` with loss of precision.

Another very noticeable difference is gerber files got a bunch of ``%LPD*%`` prefixes maybe that's innocent.

**Comment by frank-f** [comment]
> Great! With option rename [rusefi@3eb61de](https://github.com/rusefi/gerbmerge/commit/3eb61dececbffc046205882daeaca5e7851b40db) I got the script to work! But our drill files contain both PLATED and NON_PLATED so this does not look right. (open question 1) Does your fork still support combined drill files or does your fork require separate files?

As far as I can recall, I did not change the way drill files are processed. In short, I just duplicated the existing function and gave it two new names. From what I understand, if one drill file contains both types, a drill hole will be unplated, if it's not surrounded by copper.

> (open question 2) Another concern with format/precision, even if we disregard plated/non plated issue for now:
> 
> We have `T8F00S00C0.0984` which in our fork becomes `T07C0.098400` but in your fork it becomes `T07C0.098` with loss of precision.

Are you using imperial units? My projects are metric and I had to change around a lot to get metric precision scaling working right. I'll try to find a few minutes to look where your last digit is getting lost.

I am not sure what the F00S00 part of your toolchange command is supposed to mean. I can't find any documentation about this format.

> Another very noticeable difference is gerber files got a bunch of `%LPD*%` prefixes maybe that's innocent.

LPD is usually a copper pour. I don't remember working on that part, but I could imagine combining multiple PCBs with individual copper areas results in multiple LPD commands. 
Generally speaking, you can not expect to receive output files that look exactly the same as your source files. Gerbmerge parses Gerber files, stores the information in an arbitrary data structure, processes it and writes new Gerber files - in its own way. That's usually no problem. As with everything, you should inspect the result (for example with gerbv or an online gerber viewer of your board house) and if everything looks okay, the produced PCBs usually will also.

**Comment by rusefillc** [comment]
I am comparing outputs of different forks. Some extra magic is fine as long as fab shop is happy with dialect differences but loss of precision seems important. Our fab shop of choice is jlcpcb by the way

**Comment by frank-f** [comment]
The loss of the fourth digit was indeed caused by one of my former changes.

The reason for my original change was, that tool definitions were written with too many digits, six in your case. In metric mode you don't need more than three - and now imperial mode with four digits is also supported.

I use JLCPCB myself and so far they have never had any problem processing my files.

**Comment by rusefillc** [comment]
thank you!
I've checked the other test case and the merge has happened as expected!

**Comment by frank-f** [comment]
Very nice! During testing I took a look at your project and it seems very complex and impressive. Surely a use-case for gerbmerge that I would have never even thought of.
